POST http://localhost:8300/api/admin/v1/workers/login
accept: */*
Content-Type: application/json

{
  "phoneNumber": "+7 958 593 8409",
  "secretCode": ""
}

###

export SELENIUM_PROD_GRID_URL="http://31.129.96.161:4444/wd/hub"